elec<-read.csv("household_power_consumption.txt",sep=";",na.strings="?")
subset<-elec[elec$Date=="1/2/2007"|elec$Date=="2/2/2007",]
subset$DateTime=paste(subset$Date,subset$Time)
subset$DateTime<-strptime(subset$DateTime,"%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
plot(subset$DateTime,subset$Global_active_power,'l',xlab="Time",ylab="Global Active Power",main="Global Active Power")
plot(subset$DateTime,subset$Voltage,'l',xlab="dateTime",ylab="Voltage")
plot(subset$DateTime,subset$Sub_metering_1,'l',xlab="Time",ylab="Energy sub metering")
 lines(subset$DateTime,subset$Sub_metering_2,'l',col="red")
 lines(subset$DateTime,subset$Sub_metering_3,'l',col="blue")
 legend(50,50,legend=c("submetering-1","submetering-2","submetering-3"),col=c("black","red","blue"))
plot(subset$DateTime,subset$Global_reactive_power,'l',xlab="Time",ylab="Global Reactive Power")
dev.off()